### ISSUE TITLE
Throws an error on M1 hardware

### ISSUE THREAD

**Issue by makenova** [sindresorhus/macos-trash#15]
Hello,
I tried to use this on my work laptop(Apple M1 Pro) and got an error.

```
Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:412:11)
    at spawn (node:child_process:698:9)
    at execFile (node:child_process:325:17)
    at node:child_process:235:21
    at chunkedExec (file:///Users/mycomputer/.nvm/versions/node/v16.13.0/lib/node_modules/trash-cli/node_modules/trash/lib/chunked-exec.js:11:9)
    at Module.macOS (file:///Users/mycomputer/.nvm/versions/node/v16.13.0/lib/node_modules/trash-cli/node_modules/trash/lib/macos.js:14:8)
    at trash (file:///Users/mycomputer/.nvm/versions/node/v16.13.0/lib/node_modules/trash-cli/node_modules/trash/index.js:60:23)
```

The first line made me think it was an issue related to the hardware so I pulled the repo and ran the build script.
The resulting binary works without issue.

This isn't really an issue for me but more of a way to document a solution for others that might run into this problem. 😃 

made a small gist with a bit more detail on how I resolved this for myself
https://gist.github.com/makenova/eaece72c61d3c5ac082e7ce62e98b2ea

**Comment by sindresorhus** [comment]
Fixed: https://github.com/sindresorhus/macos-trash/releases/tag/v1.2.0
